{
    "MD013": false,
    "MD024": false,
    "MD007": false,
    "MD030": false,
    "MD037": false,
    "MD031": false,
    "MD041": false,
    "MD012": false,
    "MD009": false,
    "MD026": false,
    "MD036": false, 
    "MD032": false,
    "MD040": false,
    "MD033": false,
    "MD046": false,
    "MD004": false,
    "MD022": false,
    "MD049": false,
    "MD060": false,

    
}